ldm:
  base_lr: 0.000025
  params:
    timesteps: 1000
    beta_schedule: "linear"
    linear_start: 0.0015
    linear_end: 0.0195
    loss_type: "l2"
    log_every_t: 200
    clip_denoised: False
    original_elbo_weight: 0.0
    v_posterior: 0.0
    l_simple_weight: 1.0
    parameterization: "eps"
    learn_logvar: False
    logvar_init: 0.0
    unet_config:
      params:
        image_size: 56
        in_channels: 3
        out_channels: 3
        model_channels: 256
        attention_resolutions: [8,4,2]
        num_res_blocks: 2
        channel_mult: [1,2,3]
        dropout: 0.0
        conv_resample: True
        num_heads: 1
        use_scale_shift_norm: False
        resblock_updown: False
